# Generated by Django 2.0.3 on 2018-05-16 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notify',
            field=models.SlugField(default='push', verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, db_column='link_description', max_length=255, null=True, verbose_name='链接描述'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.CharField(blank=True, db_column='link_image', max_length=255, null=True, verbose_name='图像地址'),
        ),
        migrations.AlterField(
            model_name='link',
            name='notes',
            field=models.TextField(blank=True, db_column='link_notes', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='link_owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='rel',
            field=models.CharField(db_column='link_rel', default='friend', max_length=255, verbose_name='链接关系(XFN)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='rss',
            field=models.CharField(blank=True, db_column='link_rss', max_length=255, null=True, verbose_name='RSS地址'),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(db_column='link_target', default='_blank', max_length=25, verbose_name='打开方式'),
        ),
        migrations.AlterField(
            model_name='link',
            name='visible',
            field=models.CharField(blank=True, db_column='link_visible', max_length=20, null=True),
        ),
    ]
