# Generated by Django 2.0.3 on 2018-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0004_auto_20180523_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='个人站点'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_num',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
