# Generated by Django 2.0.3 on 2018-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0005_auto_20180524_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
