# Generated by Django 2.0.3 on 2018-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0007_auto_20180608_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
