# Generated by Django 2.0.3 on 2018-06-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0008_remove_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='slug',
        ),
    ]
