# Generated by Django 2.0.3 on 2018-06-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('docspace', '0009_remove_taxonomy_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='键名')),
                ('value', models.TextField(verbose_name='键值')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docspace_metadata_content_type', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name_plural': '元数据',
                'db_table': 'ds_metadatas',
                'verbose_name': '元数据',
            },
        ),
    ]
